steps:
# Dockerイメージをビルド
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'us-central1-docker.pkg.dev/$PROJECT_ID/bq-query-tool-repo/streamlit-bq-tool:$COMMIT_SHA'
    - '.'

# Artifact Registry に push
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - 'us-central1-docker.pkg.dev/$PROJECT_ID/bq-query-tool-repo/streamlit-bq-tool:$COMMIT_SHA'

# Cloud Run にデプロイ
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - run
    - deploy
    - streamlit-bq-tool
    - --image=us-central1-docker.pkg.dev/$PROJECT_ID/bq-query-tool-repo/streamlit-bq-tool:$COMMIT_SHA
    - --region=us-central1
    - --platform=managed
    - --allow-unauthenticated

images:
- 'us-central1-docker.pkg.dev/$PROJECT_ID/bq-query-tool-repo/streamlit-bq-tool:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
