steps:
# Dockerイメージをビルド
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/streamlit-bq-tool:$COMMIT_SHA', '.']

# Artifact Registry / Container Registry に push
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/streamlit-bq-tool:$COMMIT_SHA']

# Cloud Run にデプロイ
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - run
    - deploy
    - streamlit-bq-tool
    - --image=gcr.io/$PROJECT_ID/streamlit-bq-tool:$COMMIT_SHA
    - --region=us-central1
    - --platform=managed
    - --allow-unauthenticated

images:
- 'gcr.io/$PROJECT_ID/streamlit-bq-tool:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
